AllCops:
  Exclude:
    - bin/**/*
    - db/**/*
    - vendor/**/*
    - Gemfile

  DisplayCopNames: true
  DisplayStyleGuide: true
  StyleGuideCopsOnly: true

Rails:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes